browser=chrome
baseUrl=https://automationexercise.com
user=dhivyacheuwz5@gmail.com
password=123456
expectedhome=https://automationexercise.com/
ExcelFileLocation=/src/test/resources/testdata/Credential.xlsx
JsonPay=/src/test/resources/testdata/payment.json
